name: Retrain and Deploy

on:
  push:
    paths:
      - car_data.csv
      - train.py
      - app.py

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python train.py

      - name: Commit model artifacts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add model.pkl label_encoder.pkl
          git commit -m "🔁 Auto-retrained model on push" || echo "No changes to commit"
          git push

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          railwayToken: ${3ac7b4f2-ca06-4217-b441-e1165d381134}
